services:
  app: # This is the name of your SvelteKit application service
    build:
      context: . # Use the Dockerfile in the current directory
      dockerfile: Dockerfile
      image: 'eriks.day'
    container_name: 'eriks.day' # Explicit container name
    ports:
      - '3000:3000' # Map host port 3000 to container port 3000
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      # --- Add future environment variables here ---
      # - DATABASE_URL=postgres://user:password@db:5432/mydatabase
      # - API_KEY=your_secret_api_key
    restart: unless-stopped
    # volumes: # Optional: if you need to mount any volumes
    # - ./some-data:/app/data # Example
    # depends_on: # If you add a database service later
    # - db

  # --- Example: Future Database Service (e.g., PostgreSQL) ---
  # db:
  #   image: postgres:15-alpine
  #   container_name: eriks-day-db-container
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: erik
  #     POSTGRES_PASSWORD: yoursecurepassword
  #     POSTGRES_DB: eriks_day_db
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data # Persist database data
  #   ports:
  #     - "5432:5432" # Expose DB port if needed for external tools, otherwise often not needed
# volumes: # Define named volumes for data persistence (used by db service above)
#   postgres_data:
